### ISSUE TITLE
Buffer overflow in lambda function

### ISSUE THREAD

**Issue by poechsel** [AAA97AAA/SoftSec#4]
Lets take a look at the `path.cpp` file:

https://github.com/AAA97AAA/SoftSec/blob/bf4a4e95ab871f206520f2333d6742938f000d6d/src/core/path.cpp#L98-L110

The function `verify` is called by the `ScopedPath` constructor. Now a new `ScopedPath` is created during the execution of the command `cd` for exemple. It can be as long as 128 characters long. However, inside `verify_helper`, inside the call to the lambda function we will be executing `strcpy(buf+8, src)`. The `buf+8` will overflow a tiny bit is `src` is 128 characters long and will overwrite what comes just after on the stack. Here, it will overwrite the pointer to function `f` captured by the lambda function. Thus we can overwrite it with a pointer to another function like `hijack_flow`.

**Exploit**:

[This generate.py](https://gist.github.com/poechsel/288038ff815e1990a76f4dedbc05315e) file implements a pwn tool exploit that will generate an input `overflow.in` that will execute this exploit.

The file `overflow.in` (generated by `generate.py`) will execute this exploit.

**Comment by hazimeh** [comment]
You probably got it all right except for the "it will overwrite the pointer to function `f`" part.
IIRC, it actually overwrites the LSB of the next ebp in the stack to null. So when the lamba function returns, ebp is shifted by at most 0xF0 bytes in the stack.
Since the buffer is 128 bytes only, which is half of 0x100, almost 50% of the time, this exploit would result in the esp register pointing somewhere within the buffer, and thus a `ret` would pop the hijack_flow() address.
